#! /usr/bin/env python

import os.path
import sys

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GObject, GLib

def main():
    recent_mgr = Gtk.RecentManager.get_default()
    for filename in sys.argv[1:]:
        uri = GLib.filename_to_uri(os.path.abspath(filename))
        recent_mgr.add_item(uri)

    GObject.idle_add(Gtk.main_quit)
    Gtk.main()

if __name__ == '__main__':
    main()
